baseURL = 'https://eshedd.github.io/hub/'
languageCode = 'en-us'
title = 'Ethan Shedd'
theme = 'xmin'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[params]
  footer = '&copy; Ethan Shedd 2025 -- {Year} | [Github](https://github.com/eshedd) | [LinkedIn](https://linkedin.com/in/ethanshedd/)'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true